services:
  haproxy:
    restart: unless-stopped
    image: haproxy:latest
    container_name: haproxy
    user: "0:0"
    cap_add:
      - ALL                     # æˆ–è€…åªåŠ  NET_BIND_SERVICE + NET_RAW ç­‰ä½ éœ€è¦çš„
    privileged: true
    # å¯ç”¨ Host ç½‘ç»œæ¨¡å¼
    network_mode: host # ğŸ‘ˆ å…³é”®
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
